### PR TITLE
uwu

### PR DESCRIPTION
**Pull request by sourTaste000**

### CODE REVIEW

**Comment by sourTaste000** [comment]
pwease mewge uwu

**Comment by bigratenthusiast** [comment]
This pull request uses language in files that is not consistent with the GitHub Community Guidelines due to how unprofessional it is. In addition, we are not really looking to change the LICENSE.

**Comment by bigratenthusiast** [comment]
u could add kotlin though... 😳

**Comment by sourTaste000** [comment]
:trollface:

**Comment by bigratenthusiast** [comment]
🤝

**Pull request closed without merging**
